local BuildTarget = require("BuildTools.BuildTarget")
local NinjaBuildTools = require("BuildTools.NinjaBuildTools")

local EvoBuildTarget = {
	OUTPUT_FILE_NAME = NinjaBuildTools.GetExecutableName("evo"),
	BUILD_DIR = NinjaBuildTools.DEFAULT_BUILD_DIRECTORY_NAME,
	GIT_VERSION_TAG = NinjaBuildTools.DiscoverGitVersionTag(),
	-- Can't easily discover sources or resolve paths with only Lua APIs. Listing them explicitly is probably safer anyway
	-- Note that ninja doesn't care about path separators and the mingw toolchain supports forward slashes; no \ required
	luaSources = {
		-- Auto-generated versioning information for embedded libraries
		"deps/versions.lua",
		"deps/LuaJIT/LuaJIT/src/jit/p.lua",
		"deps/LuaJIT/LuaJIT/src/jit/vmdef.lua",
		"deps/LuaJIT/LuaJIT/src/jit/zone.lua",
		-- Integrated third-party code (no build system required)
		"deps/kikito/inspect.lua/inspect.lua",
		"deps/roberto-ieru/LPeg/re.lua",
		-- These modules may need some streamlining, so for now they're undocumented
		"BuildTools/NinjaBuildTools.lua",
		"BuildTools/NinjaFile.lua",
		-- Standard libraries
		"Runtime/evo.lua",
		"Runtime/API/C_CommandLine.lua",
		"Runtime/API/C_FileSystem.lua",
		"Runtime/API/C_ImageProcessing.lua",
		"Runtime/API/C_Runtime.lua",
		"Runtime/API/C_Timer.lua",
		"Runtime/API/C_WebView.lua",
		"Runtime/API/FileSystem/AsyncFileReader.lua",
		"Runtime/API/Networking/HttpServer.lua",
		"Runtime/API/Networking/WebSocketTestClient.lua",
		"Runtime/API/Networking/WebSocketServer.lua",
		"Runtime/Bindings/FFI/cpp/cpp.lua",
		"Runtime/Bindings/FFI/crypto/crypto.lua",
		"Runtime/Bindings/FFI/glfw/glfw.lua",
		"Runtime/Bindings/FFI/iconv/iconv.lua",
		"Runtime/Bindings/FFI/interop/interop.lua",
		"Runtime/Bindings/FFI/labsound/labsound.lua",
		"Runtime/Bindings/FFI/runtime/runtime.lua",
		"Runtime/Bindings/FFI/rml/rml.lua",
		"Runtime/Bindings/FFI/stbi/stbi.lua",
		"Runtime/Bindings/FFI/stduuid/stduuid.lua",
		"Runtime/Bindings/FFI/uws/uws.lua",
		"Runtime/Bindings/FFI/wgpu/wgpu.lua",
		"Runtime/Bindings/FFI/webview/webview.lua",
		"Runtime/Extensions/debugx.lua",
		"Runtime/Extensions/jsonx.lua",
		"Runtime/Extensions/packagex.lua",
		"Runtime/Extensions/stringx.lua",
		"Runtime/Extensions/tablex.lua",
		"Runtime/Libraries/assertions.lua",
		"Runtime/Libraries/bdd.lua",
		"Runtime/Libraries/console.lua",
		"Runtime/Libraries/etrace.lua",
		"Runtime/Libraries/git.lua",
		"Runtime/Libraries/oop.lua",
		"Runtime/Libraries/path.lua",
		"Runtime/Libraries/profiler.lua",
		"Runtime/Libraries/syslog.lua",
		"Runtime/Libraries/transform.lua",
		"Runtime/Libraries/uuid.lua",
		"Runtime/Libraries/validation.lua",
		"Runtime/Libraries/vfs.lua",
		"Runtime/Libraries/v8.lua",
	},
	cSources = {
		"Runtime/luajit_repl.c",
		"Runtime/Bindings/FFI/glfw_webgpu.c",
		"deps/starwing/luautf8/lutf8lib.c",
	},
	cppSources = {
		"Runtime/main.cpp",
		"Runtime/Bindings/FFI/cpp/cpp_ffi.cpp",
		"Runtime/Bindings/FFI/crypto/crypto_argon2.cpp",
		"Runtime/Bindings/FFI/crypto/crypto_ffi.cpp",
		"Runtime/Bindings/FFI/glfw/glfw_ffi.cpp",
		"Runtime/Bindings/FFI/iconv/iconv_ffi.cpp",
		"Runtime/Bindings/FFI/interop/interop_ffi.cpp",
		"Runtime/Bindings/FFI/labsound/labsound_ffi.cpp",
		"Runtime/Bindings/lpeg.cpp",
		"Runtime/Bindings/lminiz.cpp",
		"Runtime/Bindings/FFI/RmlUi_Renderer_WebGPU.cpp",
		"Runtime/Bindings/FFI/rml/rml_ffi.cpp",
		"Runtime/Bindings/FFI/runtime/runtime_ffi.cpp",
		"Runtime/Bindings/FFI/stbi/stbi_ffi.cpp",
		"Runtime/Bindings/FFI/stduuid/stduuid_ffi.cpp",
		"Runtime/Bindings/FFI/uws/uws_ffi.cpp",
		"Runtime/Bindings/FFI/wgpu/wgpu_ffi.cpp",
		"Runtime/Bindings/FFI/webview/webview_ffi.cpp",
		"Runtime/Bindings/lrexlib.cpp",
		"Runtime/Bindings/lzlib.cpp",
		"Runtime/Bindings/FFI/WebServer.cpp",
		"Runtime/LuaVirtualMachine.cpp",
	},
	includeDirectories = {
		NinjaBuildTools.DEFAULT_BUILD_DIRECTORY_NAME, -- For auto-generated headers (e.g., PCRE2)
		"Runtime",
		"Runtime/Bindings",
		"Runtime/Bindings/FFI",
		"Runtime/Bindings/FFI/cpp",
		"Runtime/Bindings/FFI/crypto",
		"Runtime/Bindings/FFI/glfw",
		"Runtime/Bindings/FFI/iconv",
		"Runtime/Bindings/FFI/interop",
		"Runtime/Bindings/FFI/labsound",
		"Runtime/Bindings/FFI/rml",
		"Runtime/Bindings/FFI/runtime",
		"Runtime/Bindings/FFI/stbi",
		"Runtime/Bindings/FFI/stduuid",
		"Runtime/Bindings/FFI/uws",
		"Runtime/Bindings/FFI/wgpu",
		"Runtime/Bindings/FFI/webview",
		"deps",
		"deps/eliemichel/glfw3webgpu",
		"deps/gfx-rs/wgpu-native/ffi",
		"deps/gfx-rs/wgpu-native/ffi/webgpu-headers/",
		"deps/glfw/glfw/include",
		"deps/LabSound/LabSound/include",
		"deps/LuaJIT/LuaJIT/src",
		"deps/luvit/luv/src",
		"deps/luvit/luv/deps/libuv/include",
		"deps/mariusbancila/stduuid/include",
		"deps/nothings/stb",
		"deps/webview/webview",
		"deps/openssl/openssl/include",
		"deps/zhaog/lua-openssl/deps/auxiliar",
		"deps/zhaog/lua-openssl/src",
		"deps/brimworks/lua-zlib",
		"deps/uNetworking/uWebSockets/src",
		"deps/uNetworking/uWebSockets/uSockets/src",
		"deps/xpol/lua-rapidjson/src",
		"deps/xpol/lua-rapidjson/rapidjson/include",
		"deps/mikke89/RmlUi/Backends",
		"deps/mikke89/RmlUi/Include",
	},
	staticLibraries = {
		"libluajit.a",
		"libluv.a",
		"libuv.a",
		"libglfw3.a",
		"libminiz.a",
		"openssl.a",
		"libpcre2-8.a",
		"librapidjson.a",
		"libssl.a",
		"libcrypto.a",
		"libwgpu_native.a",
		"uSockets.a",
		"zlibstatic.a",
		"librmlui.a",
		"librmlui_lua.a",
		"libfreetype.a",
		"libLabSound.a",
		"libLabSoundRtAudio.a",
		"libnyquist.a",
	},
	sharedLibraries = {
		Windows = {
			"psapi",
			"user32",
			"advapi32",
			"iphlpapi",
			"userenv",
			"ws2_32",
			"gdi32",
			"crypt32",
			"shell32",
			"ole32",
			"version",
			"shlwapi",
			"dbghelp",
			"uuid",
			"bcrypt",
			"d3dcompiler",
			"ntdll",
			"iconv",
			"opengl32",
			"mfplat",
			"wmcodecdspuuid",
			"mfuuid",
			"ksuser",
		},
		OSX = {
			"m",
			"dl",
			"iconv",
			"pthread",
			"Cocoa",
			"IOKit",
			"QuartzCore",
			"Metal",
			"WebKit",
			"Accelerate",
			"CoreAudio",
		},
		Linux = {
			"m",
			"dl",
			"pthread",
			"uuid",
			"webkit2gtk-4.1",
			"gtk-3",
			"gdk-3",
			"z",
			"pangocairo-1.0",
			"pango-1.0",
			"harfbuzz",
			"atk-1.0",
			"cairo-gobject",
			"cairo",
			"gdk_pixbuf-2.0",
			"soup-2.4",
			"gmodule-2.0",
			"glib-2.0",
			"gio-2.0",
			"javascriptcoregtk-4.0",
			"gobject-2.0",
			"glib-2.0",
			"pulse",
			"pulse-simple",
		},
	},
	staticallyLinkStandardLibraries = {
		Windows = true,
	},
}

return BuildTarget(EvoBuildTarget)
