local path = require("path")

local __filename = "test-path-basename.js"

assertEquals(path.win32.basename(__filename), "test-path-basename.js")
assertEquals(path.win32.basename(__filename, ".js"), "test-path-basename")
assertEquals(path.win32.basename(".js", ".js"), "")
assertEquals(path.win32.basename(""), "")
assertEquals(path.win32.basename("/dir/basename.ext"), "basename.ext")
assertEquals(path.win32.basename("/basename.ext"), "basename.ext")
assertEquals(path.win32.basename("basename.ext"), "basename.ext")
assertEquals(path.win32.basename("basename.ext/"), "basename.ext")
assertEquals(path.win32.basename("basename.ext//"), "basename.ext")
assertEquals(path.win32.basename("aaa/bbb", "/bbb"), "bbb")
assertEquals(path.win32.basename("aaa/bbb", "a/bbb"), "bbb")
assertEquals(path.win32.basename("aaa/bbb", "bbb"), "bbb")
assertEquals(path.win32.basename("aaa/bbb//", "bbb"), "bbb")
assertEquals(path.win32.basename("aaa/bbb", "bb"), "b")
assertEquals(path.win32.basename("aaa/bbb", "b"), "bb")
assertEquals(path.win32.basename("/aaa/bbb", "/bbb"), "bbb")
assertEquals(path.win32.basename("/aaa/bbb", "a/bbb"), "bbb")
assertEquals(path.win32.basename("/aaa/bbb", "bbb"), "bbb")
assertEquals(path.win32.basename("/aaa/bbb//", "bbb"), "bbb")
assertEquals(path.win32.basename("/aaa/bbb", "bb"), "b")
assertEquals(path.win32.basename("/aaa/bbb", "b"), "bb")
assertEquals(path.win32.basename("/aaa/bbb"), "bbb")
assertEquals(path.win32.basename("/aaa/"), "aaa")
assertEquals(path.win32.basename("/aaa/b"), "b")
assertEquals(path.win32.basename("/a/b"), "b")
assertEquals(path.win32.basename("//a"), "a")
assertEquals(path.win32.basename("a", "a"), "")

assertEquals(path.posix.basename(__filename), "test-path-basename.js")
assertEquals(path.posix.basename(__filename, ".js"), "test-path-basename")
assertEquals(path.posix.basename(".js", ".js"), "")
assertEquals(path.posix.basename(""), "")
assertEquals(path.posix.basename("/dir/basename.ext"), "basename.ext")
assertEquals(path.posix.basename("/basename.ext"), "basename.ext")
assertEquals(path.posix.basename("basename.ext"), "basename.ext")
assertEquals(path.posix.basename("basename.ext/"), "basename.ext")
assertEquals(path.posix.basename("basename.ext//"), "basename.ext")
assertEquals(path.posix.basename("aaa/bbb", "/bbb"), "bbb")
assertEquals(path.posix.basename("aaa/bbb", "a/bbb"), "bbb")
assertEquals(path.posix.basename("aaa/bbb", "bbb"), "bbb")
assertEquals(path.posix.basename("aaa/bbb//", "bbb"), "bbb")
assertEquals(path.posix.basename("aaa/bbb", "bb"), "b")
assertEquals(path.posix.basename("aaa/bbb", "b"), "bb")
assertEquals(path.posix.basename("/aaa/bbb", "/bbb"), "bbb")
assertEquals(path.posix.basename("/aaa/bbb", "a/bbb"), "bbb")
assertEquals(path.posix.basename("/aaa/bbb", "bbb"), "bbb")
assertEquals(path.posix.basename("/aaa/bbb//", "bbb"), "bbb")
assertEquals(path.posix.basename("/aaa/bbb", "bb"), "b")
assertEquals(path.posix.basename("/aaa/bbb", "b"), "bb")
assertEquals(path.posix.basename("/aaa/bbb"), "bbb")
assertEquals(path.posix.basename("/aaa/"), "aaa")
assertEquals(path.posix.basename("/aaa/b"), "b")
assertEquals(path.posix.basename("/a/b"), "b")
assertEquals(path.posix.basename("//a"), "a")
assertEquals(path.posix.basename("a", "a"), "")

-- On Windows a backslash acts as a path separator.
assertEquals(path.win32.basename("\\dir\\basename.ext"), "basename.ext")
assertEquals(path.win32.basename("\\basename.ext"), "basename.ext")
assertEquals(path.win32.basename("basename.ext"), "basename.ext")
assertEquals(path.win32.basename("basename.ext\\"), "basename.ext")
assertEquals(path.win32.basename("basename.ext\\\\"), "basename.ext")
assertEquals(path.win32.basename("foo"), "foo")
assertEquals(path.win32.basename("aaa\\bbb", "\\bbb"), "bbb")
assertEquals(path.win32.basename("aaa\\bbb", "a\\bbb"), "bbb")
assertEquals(path.win32.basename("aaa\\bbb", "bbb"), "bbb")
assertEquals(path.win32.basename("aaa\\bbb\\\\\\\\", "bbb"), "bbb")
assertEquals(path.win32.basename("aaa\\bbb", "bb"), "b")
assertEquals(path.win32.basename("aaa\\bbb", "b"), "bb")
assertEquals(path.win32.basename("C:"), "")
assertEquals(path.win32.basename("C:."), ".")
assertEquals(path.win32.basename("C:\\"), "")
assertEquals(path.win32.basename("C:\\dir\\base.ext"), "base.ext")
assertEquals(path.win32.basename("C:\\basename.ext"), "basename.ext")
assertEquals(path.win32.basename("C:basename.ext"), "basename.ext")
assertEquals(path.win32.basename("C:basename.ext\\"), "basename.ext")
assertEquals(path.win32.basename("C:basename.ext\\\\"), "basename.ext")
assertEquals(path.win32.basename("C:foo"), "foo")
assertEquals(path.win32.basename("file:stream"), "file:stream")
assertEquals(path.win32.basename("a", "a"), "")

-- On unix a backslash is just treated as any other character.
assertEquals(path.posix.basename("\\dir\\basename.ext"), "\\dir\\basename.ext")
assertEquals(path.posix.basename("\\basename.ext"), "\\basename.ext")
assertEquals(path.posix.basename("basename.ext"), "basename.ext")
assertEquals(path.posix.basename("basename.ext\\"), "basename.ext\\")
assertEquals(path.posix.basename("basename.ext\\\\"), "basename.ext\\\\")
assertEquals(path.posix.basename("foo"), "foo")

-- POSIX filenames may include control characters
-- c.f. http://www.dwheeler.com/essays/fixing-unix-linux-filenames.html
local controlCharFilename = string.format("Icon%s", string.char(13))
assertEquals(path.posix.basename(string.format("/a/b/%s", controlCharFilename)), controlCharFilename)
