local wgpu = require("deps.wgpu") -- Works with require and dofile (good)
dump(wgpu)

dump(package.path)
-- This does NOT work (require tries to look up the files directly - modules with more than one file will break)
-- local testfile = require("deps.wgpu.core.testfile")
-- local somefile = require("deps.wgpu.somefile")
-- printf("testfile: %s", testfile)
-- printf("somefile: %s", somefile)

-- This only works if a custom loader is implemented for the library in question
-- TBD: Can it be autogenerated for arbitrary libraries?
-- If so, still not backwards-compatible (cannot require the file directly)
-- More importantly, if the library itself consists of multiple files, that use dofile/require, it will fail (see penlight)
local testfile = require("deps.wgpu").core.testfile
local somefile = require("deps.wgpu").somefile
printf("testfile: %s", testfile)
printf("somefile: %s", somefile)
