dofile("Tests/SmokeTests/assertions-library/test-assert-equals.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-false.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-true.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-nil.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-throws.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-does-not-throw.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-failure.lua")
dofile("Tests/SmokeTests/assertions-library/test-assert-calls-function.lua")

print("OK", "The assertions library should be functional")
