describe("debug", function()
	describe("sbuf", function()
		it("should return a human-readable representation if an empty buffer was passed", function()
			local sbuf = buffer.new(0)
			local str = debug.sbuf(sbuf)
			assertEquals(str, "Buffer []")
		end)

		it("should return a human-readable representation if a non-empty buffer was passed", function()
			local sbuf = buffer.new(42):put("Hello world")
			local str = debug.sbuf(sbuf)
			assertEquals(str, "Buffer [48, 65, 6C, 6C, 6F, 20, 77, 6F, 72, 6C, 64]")
		end)
	end)
end)
