describe("debug", function()
	describe("sbuf", function()
		it("should return a human-readable representation if an empty buffer was passed", function()
			local sbuf = buffer.new(0)
			local str = debug.sbuf(sbuf)
			assertEquals(str, "Buffer []")
		end)

		it("should return a human-readable representation if a non-empty buffer was passed", function()
			local sbuf = buffer.new(42):put("ABC")
			local str = debug.sbuf(sbuf)
			assertEquals(str, "Buffer [41, 42, 43]")
		end)
	end)
end)
