local profiler = require("profiler")
local jit_profile = require("jit.p")
local jit_zone = require("jit.zone")

describe("profiler", function()
	it("should expose LuaJIT's builtin high-level profiler API", function()
		assertEquals(profiler.start, jit_profile.start)
		assertEquals(profiler.stop, jit_profile.stop)
	end)

	it("should expose LuaJIT's profiler zone API", function()
		assertEquals(profiler.zone, jit_zone)
		profiler.zone("ASDF")
		assertEquals(profiler.zone:get(), "ASDF")
		assertEquals(profiler.zone(), "ASDF")
		profiler.zone("HELLO")
		assertEquals(profiler.zone:flush())
		profiler.zone("BYE")
		assertEquals(profiler.zone(), "BYE")
	end)
end)
