name: Autoformat

on:
  pull_request:
    paths-ignore:
      - "README.MD"
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main
    paths-ignore:
      - "README.MD"
      - '.gitignore'

jobs:
  check-format:
    name: Enforce consistent formatting
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
        # Track latest MSYS2 release since the version can't be pinned, but updates may be ported with some delay
        EVO_AUTOFORMAT_VERSION: 18

    steps:
      # MSYS needs to be available before running any git commands
      - name: Install clang-format (via MSYS)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: git mingw-w64-x86_64-clang

      - name: Disable autocrlf # Messes up everything on Windows since the formatter applies \n
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up StyLua
        uses: JohnnyMorganz/stylua-action@v3.0.0 # TBD update?
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check . --verbose
          version: v0.20.0 # TBD update?

        # The preinstalled version is positively antique; replace with the latest and greatest (to match MSYS)
      - name: Install clang-format (via APT)
        if: runner.os == 'Linux'
        run: ./deps/install-clang-format.sh

      # TODO link on windows and macOS
      - name: Install clang-format (via Homebrew)
        if: runner.os == 'macOS'
        run: |
          set -eu
          brew install llvm@${{ env.EVO_AUTOFORMAT_VERSION }}
          ls -l /opt/homebrew/opt/llvm@${{ env.EVO_AUTOFORMAT_VERSION }}/bin
          echo "/opt/homebrew/opt/llvm@${{ env.EVO_AUTOFORMAT_VERSION }}/bin" >> $GITHUB_PATH

      - name: Create versioned clang-format- alias (Windows and macOS)
        if: runner.os != 'Linux'
        run: |
          set -eu
          ln -s $(which clang-format) $(which clang-format)-{ env.EVO_AUTOFORMAT_VERSION }}

      - name: Verify clang-format version
        run: clang-format --version && clang-format-${{ env.EVO_AUTOFORMAT_VERSION }} --version

      - name: Run autoformat (Windows)
        if: runner.os == 'Windows'
        run: ./autoformat.sh
        shell: msys2 {0}

      - name: Run autoformat (Linux and macOS)
        if: runner.os != 'Windows'
        run: ./autoformat.sh

      - name: Check for inconsistent formatting # todo remove this, seems obsolete/redundant?
        run: git --no-pager diff --exit-code -b . #The -b is for inconsistent newlines, which we ignore (for now)
