name: Build and Release (Mac OS)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  create:
    # Any branch or tag

jobs:
  build:
    name: Build for Mac OS
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: "0" # Required so that git describe actually works (and we can embed the version tag)

      - name: Install Ninja
        run: brew install ninja

      - name: Build luajit
        run: deps/luajit-unixbuild.sh && ls ninjabuild-unix

      - name: Build luv and libuv
        run: deps/luv-unixbuild.sh && ls ninjabuild-unix

      - name: Build runtime
        run: ls && ./unixbuild.sh && ls ninjabuild-unix && cp ninjabuild-unix/evo . && ls

      - name: Run smoke tests
        run: ./evo Tests/smoke-test.lua

      - name: Prepare artifacts
        run: cp evo evo-macos-x64

      - name: Publish new release
        # Truly "continuous" releases may be overkill here, so better only release tagged versions
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: evo-macos-x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
